### ISSUE TITLE
explain sd-jwt vc without SD better

### ISSUE THREAD

**Issue by Sakurann** [vcstuff/oauth-sd-jwt-vc#151]
it would be beneficial to explain sd-jwt vc without SD better.
explanation that seem to resonate is something along the lines of:

> it's the difference in framing. selective disclosure now becomes a feature of one credential format. no more of "i use credential format A (current vc-jwt) because i do not need SD, i use credential format B (original sd-jwt vc) because i need SD". now, it's "i use sd-jwt vc and turn on SD feature on and off depending on the use-case" - so it's better for the interop and the code base.

**Comment by danielfett** [comment]
Addressed in #160.
